#ifndef _FOOBAR_SEAPLUS_API_MAPPING_H_
#define _FOOBAR_SEAPLUS_API_MAPPING_H_

/* This header file has been generated by the Seaplus integration
 * bridge for the 'foobar' service, on 2019/3/9 18:43:46.
 */

/* For each of the exposed functions of the API, 
 * a Seaplus identifier is generated to ensure that 
 * the C code of the driver can stay in sync with the 
 * Erlang view on said API, regardless of its changes.
 */

#define FOO_1_ID 1
#define BAR_2_ID 2
#define BAZ_2_ID 3
#define TUR_0_ID 4
#define FROB_1_ID 5

#endif // _FOOBAR_SEAPLUS_API_MAPPING_H_
