#ifndef _FOOBAR_SEAPLUS_API_MAPPING_H_
#define _FOOBAR_SEAPLUS_API_MAPPING_H_

/*
 * Hand-made version of the mapping header file to be generated by the Seaplus
 * parse transform.
 *
 * It defines, on the C side as well, the mapping between a function (ex: foo)
 * and its Seaplus identifier (ex: 1). Of course these identifiers must match
 * their Erlang counterparts.
 *
 */

#define FOO_1_ID  1
#define BAR_2_ID  2
#define BAZ_2_ID  3
#define TUR_0_ID  4
#define FROB_1_ID 5


#endif // _FOOBAR_SEAPLUS_API_MAPPING_H_
