name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    # See https://hub.docker.com/_/erlang:
    container:
      image: erlang:latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: |
        rebar3 compile
        #echo " - building from: $(pwd)"
        #echo " - content of parent directory: $(ls .. 2>/dev/null | tr '\n' ' ')"
        #echo " - content of _checkouts directory: $(ls _checkouts 2>/dev/null)"
        #echo " - content of _build/default/lib directory: $(ls _build/default/lib 2>/dev/null)"
        make info-context
    - name: Run tests
      run: make test NODE_NAMING="--sn"
